name: GeneralFunctionPlugin
main: com.gmail.panmpan.GeneralFunctionPlugin.GeneralFunctionPlugin
version: 1.3
author: Michael Pan
commands:
  nick:
    description: 改變你的暱稱
    usage: /<command> <暱稱>
  lightning:
    description: 召喚閃電在玩家身上
    usage: /<command> [player]
    permission: op
  sethome:
    description: 在目前的位置設定家
    usage: /<command>
  home:
    description: 傳送到家的位置
    usage: /<command>
  # visit:
  #   description: 造訪別人的家
  #   usage: /<command>
  #   permission: op