name: GeneralFunctionPlugin
main: com.gmail.panmpan.GeneralFunctionPlugin.GeneralFunctionPlugin
version: 1.4
author: Michael Pan
commands:
  nick:
    description: 改變你的暱稱
    usage: /<command> <暱稱>
    aliases: [n]
  lightning:
    description: 召喚閃電在玩家身上
    usage: /<command> [玩家]
    permission: op
    aliases: [l]
  home:
    description: /home 傳送到家。 /home s 設定新家。 /home v <玩家名稱> 拜訪其他人家
    usage: /<command> [s/v]
    aliases: [h]
  allow-list:
    description: 列出 /allow-list 相關的指令
    usage: /<command> [add|remove|removei|list]
    aliases: [a]